# Site settings
exclude: [README.md]
title: Bettina's Pen
email: bettinaspen@gmail.com
description: > # this symbol means ignore newlines until "baseurl:"
    Here you will find details about my work.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://bettinaspen.github.io" # the base hostname & protocol for your site
#paginate: 3


# Build settings
markdown: kramdown
